// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "example.com/examples/api/layered/models"
)

// UserReader is an autogenerated mock type for the userReader type
type UserReader struct {
	mock.Mock
}

type UserReader_Expecter struct {
	mock *mock.Mock
}

func (_m *UserReader) EXPECT() *UserReader_Expecter {
	return &UserReader_Expecter{mock: &_m.Mock}
}

// ReadUser provides a mock function with given fields: ctx, id
func (_m *UserReader) ReadUser(ctx context.Context, id uint64) (models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) models.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserReader_ReadUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUser'
type UserReader_ReadUser_Call struct {
	*mock.Call
}

// ReadUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *UserReader_Expecter) ReadUser(ctx interface{}, id interface{}) *UserReader_ReadUser_Call {
	return &UserReader_ReadUser_Call{Call: _e.mock.On("ReadUser", ctx, id)}
}

func (_c *UserReader_ReadUser_Call) Run(run func(ctx context.Context, id uint64)) *UserReader_ReadUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *UserReader_ReadUser_Call) Return(_a0 models.User, _a1 error) *UserReader_ReadUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserReader_ReadUser_Call) RunAndReturn(run func(context.Context, uint64) (models.User, error)) *UserReader_ReadUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserReader creates a new instance of UserReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserReader {
	mock := &UserReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
