// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "example.com/examples/api/layered/internal/models"
)

// UserCreator is an autogenerated mock type for the userCreator type
type UserCreator struct {
	mock.Mock
}

type UserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCreator) EXPECT() *UserCreator_Expecter {
	return &UserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserCreator) CreateUser(ctx context.Context, user models.User) (models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *UserCreator_Expecter) CreateUser(ctx interface{}, user interface{}) *UserCreator_CreateUser_Call {
	return &UserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserCreator_CreateUser_Call) Run(run func(ctx context.Context, user models.User)) *UserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *UserCreator_CreateUser_Call) Return(_a0 models.User, _a1 error) *UserCreator_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserCreator_CreateUser_Call) RunAndReturn(run func(context.Context, models.User) (models.User, error)) *UserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCreator creates a new instance of UserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreator {
	mock := &UserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
