FROM golang:1.24.3-alpine AS build

WORKDIR /app

# Copy only go.mod and go.sum first to leverage Docker cache
COPY go.mod ./ go.sum ./
RUN go mod download

# Copy only necessary source files
COPY ./cmd/ ./cmd/ ./internal/ ./internal/

# Build with optimizations
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o /bin/bootstrap \
    ./cmd/api/.

FROM gcr.io/distroless/static-debian12 AS publish

# Copy only the compiled binary
COPY --from=build /bin/bootstrap /bin/bootstrap

# switch to an unprivileged user# switch to an unprivileged user

USER nonroot:nonroot

EXPOSE 8080

ENTRYPOINT ["/bin/bootstrap"]