FROM golang:1.24.3-alpine3.21 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum* ./
RUN go mod download

COPY .. .
RUN go build -o ./app ./cmd/api/.

FROM alpine:3.21 AS publish

WORKDIR /app

COPY --from=build ./app .

EXPOSE 8080

ENTRYPOINT [ "./app" ]